import type { MetricConfig, ModelConfig } from "@/types";

const now = new Date().toISOString();

export const defaultModels: ModelConfig[] = [
  {
    id: "or-gpt-4o-mini",
    provider: "openrouter",
    modelId: "openai/gpt-4o-mini",
    displayName: "GPT-4o mini",
    contextWindow: 128000,
    inputPricePer1k: 0.00015,
    outputPricePer1k: 0.0006,
    enabled: true,
    isDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "or-claude-3-5-haiku",
    provider: "openrouter",
    modelId: "anthropic/claude-3.5-haiku",
    displayName: "Claude 3.5 Haiku",
    contextWindow: 200000,
    inputPricePer1k: 0.0008,
    outputPricePer1k: 0.004,
    enabled: true,
    isDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "or-gemini-3-flash-preview",
    provider: "openrouter",
    modelId: "google/gemini-3-flash-preview",
    displayName: "Gemini 3 Flash Preview",
    contextWindow: 1048576,
    inputPricePer1k: 0.0005,
    outputPricePer1k: 0.003,
    enabled: true,
    isDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "or-llama-3-1-70b",
    provider: "openrouter",
    modelId: "meta-llama/llama-3.1-70b-instruct",
    displayName: "Llama 3.1 70B Instruct",
    contextWindow: 128000,
    inputPricePer1k: 0.00088,
    outputPricePer1k: 0.00088,
    enabled: false,
    isDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "nim-llama-3-1-70b",
    provider: "nvidia-nim",
    modelId: "meta/llama-3.1-70b-instruct",
    displayName: "NIM Llama 3.1 70B",
    contextWindow: 128000,
    inputPricePer1k: 0,
    outputPricePer1k: 0,
    enabled: false,
    isDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "nim-mixtral-8x7b",
    provider: "nvidia-nim",
    modelId: "mistralai/mixtral-8x7b-instruct-v0.1",
    displayName: "NIM Mixtral 8x7B",
    contextWindow: 32768,
    inputPricePer1k: 0,
    outputPricePer1k: 0,
    enabled: false,
    isDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "nim-nemotron-3-super-120b-a12b",
    provider: "nvidia-nim",
    modelId: "nvidia/nemotron-3-super-120b-a12b",
    displayName: "Nemotron-3 Super 120B",
    contextWindow: 1000000,
    inputPricePer1k: 0,
    outputPricePer1k: 0,
    enabled: false,
    isDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "nim-qwen-3-5-122b",
    provider: "nvidia-nim",
    modelId: "qwen/qwen3.5-122b-a10b",
    displayName: "Qwen 3.5 122B",
    contextWindow: 262144,
    inputPricePer1k: 0,
    outputPricePer1k: 0,
    enabled: false,
    isDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "nim-mistral-small-4",
    provider: "nvidia-nim",
    modelId: "mistralai/mistral-small-4-119b-2603",
    displayName: "mistral-small-4",
    contextWindow: 256000,
    inputPricePer1k: 0,
    outputPricePer1k: 0,
    enabled: false,
    isDefault: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const defaultMetrics: MetricConfig[] = [
  {
    id: "accuracy",
    key: "accuracy",
    label: "Accuracy",
    description: "How correct and factually sound the answer appears.",
  },
  {
    id: "instruction-following",
    key: "instruction_following",
    label: "Instruction-following",
    description: "How well the response follows the prompt and constraints.",
  },
  {
    id: "tone-style-fit",
    key: "tone_style_fit",
    label: "Tone/style fit",
    description: "How well the response matches the desired voice or format.",
  },
  {
    id: "completeness",
    key: "completeness",
    label: "Completeness",
    description: "How fully the response covers the request.",
  },
  {
    id: "hallucination-risk",
    key: "hallucination_risk",
    label: "Hallucination risk",
    description: "How likely the answer contains unsupported or invented claims.",
  },
];
